server {
    listen 80;
    server_name localhost;
    client_max_body_size 0;

 location / {
        root /usr/share/nginx/html/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        client_max_body_size 0;

        resolver 127.0.0.11 valid=30s;

        set $backend http://storage_app:8080;

        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
